import './globals.css'
import { Gabarito } from 'next/font/google'
import { NavBar } from "@/components/NavBar"

const gabarito = Gabarito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
        <NavBar/> 
        {children}
        </body>
    </html>
  )
}
